### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by manotejmeka** [manotejmeka/MI-449-SS17-741-html-more-kinds-of-content-OSB7Pe#1]
@KatieMFritz Can you take a look at this? It's [hosted here](https://manotejmeka.github.io/MI-449-SS17-741-html-more-kinds-of-content-OSB7Pe/) and meets the following criteria:

- [x] Include [a haiku](http://www.kidzone.ws/poetry/haiku.htm), describing the feelings this product will evoke (with `br` elements to add new lines where appropriate)
- [x] [Create and download a sound effect file](http://sfbgames.com/chiptone/) for what the game will sound like when you win, then include an audio player in the page so users can hear the sample
- [x] Include a table comparing which features your game has in comparison to competitors (these competitors may be real or made up)
- [x] Include a demo video from YouTube, but featuring a completely unrelated animal being cute (not getting hurt!)

**Comment by KatieMFritz** [comment]
Hi Manotej, looking forward to reviewing this! 🙂 

I ran it through the [W3 Validator site](https://validator.w3.org/nu/?doc=https%3A%2F%2Fmanotejmeka.github.io%2FMI-449-SS17-741-html-more-kinds-of-content-OSB7Pe%2F) and there are some errors. Take a look and **see if you can get all the errors cleaned up, then resubmit it** and I'll evaluate it for the project criteria. 

**Tip:** I appreciate the layout and styling you've added, but for this project, it might help to leave that out and stick to the basics. We'll be getting to fancy layout and styles very soon!

**Comment by manotejmeka** [comment]
@KatieMFritz I have fixed the changes you have asked for

**Comment by KatieMFritz** [comment]
Great, thank you!

Your game sounds much better than your competitor's game. 😄  Also, baby turtles! So cool. 🐢 

**The good news:** the code is valid now, and you did an excellent job using the new elements from the lesson. Your `br`, `audio`, `iframe`, and `table` all work great. 

**The bad news:** these lessons are cumulative, so I'm going to make you fix your semantic, indentation, and spacing issues! And if you're going to use Bootstrap, I want you to use it correctly, so I've got some feedback on that too. 😛 

### Using headings appropriately.

Back on [page 3 of the basic HTML elements lesson](https://msu.lansing.codes/courses/MI-449-SS17-741/lessons/html-atom-and-basic-elements/3), we introduced headings. We didn't talk a whole lot about how to use them though. Here's some more information.

Headings (`h1`, `h2`, and so on) create a structured outline of the page. The name of the page should always be `h1` (and usually, that should be the *only* `h1` on the page). The main sections of the page should be labeled with `h2`, and sections that go under the `h2` sections should be `h3`. **[Check out this example](http://codepen.io/KatieMFritz/pen/MJpWGg/?editors=1000#0) to see what I mean.**

- Right now, your page title is "Haiku," and your `h1` also says "Haiku." But that's not the name of the fake game you are promoting, right? The page title and the `h1` should both be the main topic of the page (your fake game name). 
- For the sections on the page, like "Game summary," "Haiku," and "Features," `h2` would be the most appropriate heading. These are the second-most important titles on the page, right? 


### Consistent indentation

From the lesson:

> Always indent lines by the same amount

Some of your code uses 2-space indentation, and some uses 4-space indentation. For our class, 2-space indentation is the standard.

[Page 3 of the lesson](https://msu.lansing.codes/courses/MI-449-SS17-741/lessons/html-boilerplate-linting-and-code-style/3), in the section *Settings to better see indentation*, has some tips for avoiding this in your revisions and beyond. 


### Consistent Spacing

Within and between lines, you have some inconsistent spacing. It's okay to use line breaks between sections of your code, but be sure to put the same number of empty lines before and after those sections. 

Check out the *Consistent Spacing* section on [page 3 of the lesson](https://msu.lansing.codes/courses/MI-449-SS17-741/lessons/html-boilerplate-linting-and-code-style/3) for examples of consistent and inconsistent spacing.  You can make up your own standards for spacing, but it's important to stick to them throughout a project so your code is easier for others (and your future self!) to read and understand. 

### Bootstrap/Layout

I applaud your initiative at using Bootstrap to make your site prettier! 👏 There are some layout issues though.

1. When you look at your hosted page, the content is wider than the screen. I checked your `.container`, `.column`, and `.row` divs, and they look correct (nice job with the nested indentation on those - it definitely makes it easier to read). I think the problem is actually with the `width` attribute on your `iframe`. Try changing it to `100%` and see if that helps. You could also change your column widths so the column with the YouTube video is wider; however, you'll still have problems with responsiveness as long as the `iframe` has a fixed `width`. Let me know if you are confused about that and I'll be happy to explain further.
2. There seems to be an extra, empty `div` (with class `.content`) at the end of your code. Is that on purpose? If not, get rid of it - you never want to leave extra stuff to clutter up your code. It can cause layout or behavior problems, or at the very least, it's confusing for reviewers!

#### Extra credit (well, not really - but it's an optional way to go above and beyond)

This isn't required at all, but if you want to make your `h1` centered on the page (once you change it to the name of your game), here's how you would do it with Bootstrap:

(right after `<div class="container">` and before `<div class="row">`)

```
<div class="row">
  <div class="col-xs-12">
    <h1 class="text-center">Name of your game</h1>
  </div><!-- /.col-xs-12 -->
</div><!-- /.row -->
```

When I'm using Bootstrap or another grid system that requires a lot of nested `div`s, I like to use comments to keep track of which `div` I'm closing. It's not a universal requirement, just something else that some developers do to make code easier to read.

===

Whew! I know that's a lot of comments. It's not as bad as it looks, though. Please ask if you have any questions about any of that. 😄

**Comment by manotejmeka** [comment]
@KatieMFritz Thank you very much for the detailed feedback. I really appreciate it. I have made the changes you have asked for. Please let me know if there are anything else you would like me to fix.

**Comment by KatieMFritz** [comment]
Manotej, nice job cleaning this up! 🎉 It's way better (and the hosted site looks great!) but there are three small inconsistencies I'm still seeing:

1. Extra line break before `</head>`
2. 4-space indentation inside the `table` element
3. `title` is still "Haiku" not "Race Cars"

Baby turtles are still sweet. 😄

**Comment by manotejmeka** [comment]
@KatieMFritz I have made those changes!!

**Comment by KatieMFritz** [comment]
It's awesome! 🎉 :shipit: 

A note for future projects: 

### Why we use unique, descriptive commit messages

So, the beauty of git is that by making regular commits, you give yourself lots of "save points." If you mess up later, you can go back to when it was working. 

This is a lot easier if each commit has a unique message explaining exactly what changed in that commit. However, for this project, a lot of your commits just reference errors or bug fixes, which is pretty vague. You also used the same commit messages more than once. If you (or another developer partner) needed to go back to a previous commit, you'd have to look at your code to figure out what changed, instead of being able to tell quickly from the commit log. 

Your commit message `adding the music file` is great - I know exactly what changed in that commit. Some other messages you might have used include:

- `clean up indentation, remove extra line break before </head>, and change title`
- `fix errors from W3 validator`
- `update headings and indentation, change iframe width`

Do those make sense to you? They don't have to be pretty or eloquent, just descriptive. 

You don't have to worry about _redoing_ any of this - but in the future, try giving each commit its own specific message describing what you just changed. It will help you be even more of a git wizard, and help you work better with other developers. 💪
